//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ProjectWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_ProjectEntities : DbContext
    {
        public MVC_ProjectEntities()
            : base("name=MVC_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student2> student2 { get; set; }
        public virtual DbSet<sale> sales { get; set; }

        public System.Data.Entity.DbSet<MVC_ProjectWork.Models.user> users { get; set; }
    }
}
