//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ProjectWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class student2
    {
        public int id { get; set; }
        public string name { get; set; }
        public string @class { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string picturepath { get; set; }
    }
}
