//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ProjectWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public string sale_id { get; set; }
        public string product_id { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> sales_price { get; set; }
        public Nullable<decimal> Total_price { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
